# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message/gateway/device_input.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.message import header_pb2 as common_dot_message_dot_header__pb2
from common.message import geometry_pb2 as common_dot_message_dot_geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message/gateway/device_input.proto',
  package='citibot.common.message',
  syntax='proto2',
  serialized_pb=_b('\n)common/message/gateway/device_input.proto\x12\x16\x63itibot.common.message\x1a\x1b\x63ommon/message/header.proto\x1a\x1d\x63ommon/message/geometry.proto\";\n\nDeviceInfo\x12\x13\n\x0b\x64\x65vice_name\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65vice_timestamp\x18\x02 \x01(\x04\"d\n\x0f\x45xternalGpsInfo\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12-\n\x03gps\x18\x02 \x01(\x0b\x32 .citibot.common.message.PointLLH\x12\x0f\n\x07heading\x18\x03 \x01(\x01\"\xb4\x01\n\x0e\x44\x65viceInputMsg\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.citibot.common.message.Header\x12=\n\x0c\x65xternal_gps\x18\x02 \x01(\x0b\x32\'.citibot.common.message.ExternalGpsInfo\x12\x33\n\x07\x64\x65vices\x18\x03 \x03(\x0b\x32\".citibot.common.message.DeviceInfo')
  ,
  dependencies=[common_dot_message_dot_header__pb2.DESCRIPTOR,common_dot_message_dot_geometry__pb2.DESCRIPTOR,])




_DEVICEINFO = _descriptor.Descriptor(
  name='DeviceInfo',
  full_name='citibot.common.message.DeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_name', full_name='citibot.common.message.DeviceInfo.device_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_timestamp', full_name='citibot.common.message.DeviceInfo.device_timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=188,
)


_EXTERNALGPSINFO = _descriptor.Descriptor(
  name='ExternalGpsInfo',
  full_name='citibot.common.message.ExternalGpsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='citibot.common.message.ExternalGpsInfo.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps', full_name='citibot.common.message.ExternalGpsInfo.gps', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='citibot.common.message.ExternalGpsInfo.heading', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=290,
)


_DEVICEINPUTMSG = _descriptor.Descriptor(
  name='DeviceInputMsg',
  full_name='citibot.common.message.DeviceInputMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='citibot.common.message.DeviceInputMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_gps', full_name='citibot.common.message.DeviceInputMsg.external_gps', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='devices', full_name='citibot.common.message.DeviceInputMsg.devices', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=473,
)

_EXTERNALGPSINFO.fields_by_name['gps'].message_type = common_dot_message_dot_geometry__pb2._POINTLLH
_DEVICEINPUTMSG.fields_by_name['header'].message_type = common_dot_message_dot_header__pb2._HEADER
_DEVICEINPUTMSG.fields_by_name['external_gps'].message_type = _EXTERNALGPSINFO
_DEVICEINPUTMSG.fields_by_name['devices'].message_type = _DEVICEINFO
DESCRIPTOR.message_types_by_name['DeviceInfo'] = _DEVICEINFO
DESCRIPTOR.message_types_by_name['ExternalGpsInfo'] = _EXTERNALGPSINFO
DESCRIPTOR.message_types_by_name['DeviceInputMsg'] = _DEVICEINPUTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEINFO,
  __module__ = 'common.message.gateway.device_input_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.DeviceInfo)
  ))
_sym_db.RegisterMessage(DeviceInfo)

ExternalGpsInfo = _reflection.GeneratedProtocolMessageType('ExternalGpsInfo', (_message.Message,), dict(
  DESCRIPTOR = _EXTERNALGPSINFO,
  __module__ = 'common.message.gateway.device_input_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.ExternalGpsInfo)
  ))
_sym_db.RegisterMessage(ExternalGpsInfo)

DeviceInputMsg = _reflection.GeneratedProtocolMessageType('DeviceInputMsg', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEINPUTMSG,
  __module__ = 'common.message.gateway.device_input_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.DeviceInputMsg)
  ))
_sym_db.RegisterMessage(DeviceInputMsg)


# @@protoc_insertion_point(module_scope)
