# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message/map/map_parking_space.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.message.map import map_geometry_pb2 as common_dot_message_dot_map_dot_map__geometry__pb2
from common.message.map import map_id_pb2 as common_dot_message_dot_map_dot_map__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message/map/map_parking_space.proto',
  package='citibot.common.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n*common/message/map/map_parking_space.proto\x12\x14\x63itibot.common.hdmap\x1a%common/message/map/map_geometry.proto\x1a\x1f\x63ommon/message/map/map_id.proto\"\xa2\x03\n\x0cParkingSpace\x12$\n\x02id\x18\x01 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12.\n\x07polygon\x18\x02 \x01(\x0b\x32\x1d.citibot.common.hdmap.Polygon\x12,\n\noverlap_id\x18\x03 \x03(\x0b\x32\x18.citibot.common.hdmap.Id\x12\x0f\n\x07heading\x18\x04 \x01(\x01\x12:\n\x04type\x18\x64 \x01(\x0e\x32\'.citibot.common.hdmap.ParkingSpace.Type:\x03\x41LL\x12\x0c\n\x04name\x18\x65 \x01(\t\x12\x10\n\x08\x64istance\x18\x66 \x01(\x01\"\xa0\x01\n\x04Type\x12\x07\n\x03\x41LL\x10\x01\x12\x07\n\x03\x43\x41R\x10\x02\x12\t\n\x05WOMEN\x10\x03\x12\x0f\n\x0bHANDICAPPED\x10\x04\x12\x07\n\x03\x42US\x10\x05\x12\t\n\x05TRUCK\x10\x06\x12\x0c\n\x08\x45LECTRIC\x10\x07\x12\r\n\tRESIDENTS\x10\x08\x12\x0f\n\x0b\x42US_STATION\x10\t\x12\x0c\n\x08PLATFORM\x10\x33\x12\x0b\n\x07LOADING\x10\x34\x12\r\n\tUNLOADING\x10\x35\"\x90\x01\n\nParkingLot\x12$\n\x02id\x18\x01 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12.\n\x07polygon\x18\x02 \x01(\x0b\x32\x1d.citibot.common.hdmap.Polygon\x12,\n\noverlap_id\x18\x03 \x03(\x0b\x32\x18.citibot.common.hdmap.Id')
  ,
  dependencies=[common_dot_message_dot_map_dot_map__geometry__pb2.DESCRIPTOR,common_dot_message_dot_map_dot_map__id__pb2.DESCRIPTOR,])



_PARKINGSPACE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='citibot.common.hdmap.ParkingSpace.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WOMEN', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HANDICAPPED', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUS', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRUCK', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ELECTRIC', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESIDENTS', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUS_STATION', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLATFORM', index=9, number=51,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOADING', index=10, number=52,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNLOADING', index=11, number=53,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=399,
  serialized_end=559,
)
_sym_db.RegisterEnumDescriptor(_PARKINGSPACE_TYPE)


_PARKINGSPACE = _descriptor.Descriptor(
  name='ParkingSpace',
  full_name='citibot.common.hdmap.ParkingSpace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='citibot.common.hdmap.ParkingSpace.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='citibot.common.hdmap.ParkingSpace.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overlap_id', full_name='citibot.common.hdmap.ParkingSpace.overlap_id', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='citibot.common.hdmap.ParkingSpace.heading', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='citibot.common.hdmap.ParkingSpace.type', index=4,
      number=100, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='citibot.common.hdmap.ParkingSpace.name', index=5,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='citibot.common.hdmap.ParkingSpace.distance', index=6,
      number=102, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PARKINGSPACE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=559,
)


_PARKINGLOT = _descriptor.Descriptor(
  name='ParkingLot',
  full_name='citibot.common.hdmap.ParkingLot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='citibot.common.hdmap.ParkingLot.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='citibot.common.hdmap.ParkingLot.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overlap_id', full_name='citibot.common.hdmap.ParkingLot.overlap_id', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=706,
)

_PARKINGSPACE.fields_by_name['id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_PARKINGSPACE.fields_by_name['polygon'].message_type = common_dot_message_dot_map_dot_map__geometry__pb2._POLYGON
_PARKINGSPACE.fields_by_name['overlap_id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_PARKINGSPACE.fields_by_name['type'].enum_type = _PARKINGSPACE_TYPE
_PARKINGSPACE_TYPE.containing_type = _PARKINGSPACE
_PARKINGLOT.fields_by_name['id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_PARKINGLOT.fields_by_name['polygon'].message_type = common_dot_message_dot_map_dot_map__geometry__pb2._POLYGON
_PARKINGLOT.fields_by_name['overlap_id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
DESCRIPTOR.message_types_by_name['ParkingSpace'] = _PARKINGSPACE
DESCRIPTOR.message_types_by_name['ParkingLot'] = _PARKINGLOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ParkingSpace = _reflection.GeneratedProtocolMessageType('ParkingSpace', (_message.Message,), dict(
  DESCRIPTOR = _PARKINGSPACE,
  __module__ = 'common.message.map.map_parking_space_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.hdmap.ParkingSpace)
  ))
_sym_db.RegisterMessage(ParkingSpace)

ParkingLot = _reflection.GeneratedProtocolMessageType('ParkingLot', (_message.Message,), dict(
  DESCRIPTOR = _PARKINGLOT,
  __module__ = 'common.message.map.map_parking_space_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.hdmap.ParkingLot)
  ))
_sym_db.RegisterMessage(ParkingLot)


# @@protoc_insertion_point(module_scope)
