# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message/dispatch/bp_network.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.message.map import map_id_pb2 as common_dot_message_dot_map_dot_map__id__pb2
from common.message import geometry_pb2 as common_dot_message_dot_geometry__pb2
from common.message.routing import routing_pb2 as common_dot_message_dot_routing_dot_routing__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message/dispatch/bp_network.proto',
  package='citibot.common.dispatch',
  syntax='proto2',
  serialized_pb=_b('\n(common/message/dispatch/bp_network.proto\x12\x17\x63itibot.common.dispatch\x1a\x1f\x63ommon/message/map/map_id.proto\x1a\x1d\x63ommon/message/geometry.proto\x1a$common/message/routing/routing.proto\"\xfc\x01\n\x0f\x44\x65stinationInfo\x12;\n\x04type\x18\x01 \x02(\x0e\x32-.citibot.common.dispatch.DestinationInfo.Type\x12$\n\x02id\x18\x02 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12\x32\n\x08position\x18\x03 \x01(\x0b\x32 .citibot.common.message.PointENU\"R\n\x04Type\x12\x08\n\x04NONE\x10\x01\x12\x14\n\x10\x43RUSHING_STATION\x10\x02\x12\x13\n\x0fLOADING_STATION\x10\x03\x12\x15\n\x11UNLOADING_STATION\x10\x04\"\xb9\x02\n\tBPRouting\x12$\n\x02id\x18\x01 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12-\n\x0b\x66rom_loc_id\x18\x02 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12+\n\tto_loc_id\x18\x03 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12\x36\n\x05route\x18\x04 \x01(\x0b\x32\'.citibot.common.routing.RoutingResponse\x12\x33\n\tpathpoint\x18\x05 \x03(\x0b\x32 .citibot.common.message.PointENU\x12=\n\x0b\x64\x65stination\x18\x06 \x01(\x0b\x32(.citibot.common.dispatch.DestinationInfo\"W\n\tBPNetwork\x12\x15\n\rhdmap_version\x18\x01 \x01(\t\x12\x33\n\x07routing\x18\x02 \x03(\x0b\x32\".citibot.common.dispatch.BPRouting')
  ,
  dependencies=[common_dot_message_dot_map_dot_map__id__pb2.DESCRIPTOR,common_dot_message_dot_geometry__pb2.DESCRIPTOR,common_dot_message_dot_routing_dot_routing__pb2.DESCRIPTOR,])



_DESTINATIONINFO_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='citibot.common.dispatch.DestinationInfo.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CRUSHING_STATION', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOADING_STATION', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNLOADING_STATION', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=342,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_DESTINATIONINFO_TYPE)


_DESTINATIONINFO = _descriptor.Descriptor(
  name='DestinationInfo',
  full_name='citibot.common.dispatch.DestinationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='citibot.common.dispatch.DestinationInfo.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='citibot.common.dispatch.DestinationInfo.id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='position', full_name='citibot.common.dispatch.DestinationInfo.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DESTINATIONINFO_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=424,
)


_BPROUTING = _descriptor.Descriptor(
  name='BPRouting',
  full_name='citibot.common.dispatch.BPRouting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='citibot.common.dispatch.BPRouting.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from_loc_id', full_name='citibot.common.dispatch.BPRouting.from_loc_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_loc_id', full_name='citibot.common.dispatch.BPRouting.to_loc_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route', full_name='citibot.common.dispatch.BPRouting.route', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pathpoint', full_name='citibot.common.dispatch.BPRouting.pathpoint', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destination', full_name='citibot.common.dispatch.BPRouting.destination', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=740,
)


_BPNETWORK = _descriptor.Descriptor(
  name='BPNetwork',
  full_name='citibot.common.dispatch.BPNetwork',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hdmap_version', full_name='citibot.common.dispatch.BPNetwork.hdmap_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='routing', full_name='citibot.common.dispatch.BPNetwork.routing', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=742,
  serialized_end=829,
)

_DESTINATIONINFO.fields_by_name['type'].enum_type = _DESTINATIONINFO_TYPE
_DESTINATIONINFO.fields_by_name['id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_DESTINATIONINFO.fields_by_name['position'].message_type = common_dot_message_dot_geometry__pb2._POINTENU
_DESTINATIONINFO_TYPE.containing_type = _DESTINATIONINFO
_BPROUTING.fields_by_name['id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_BPROUTING.fields_by_name['from_loc_id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_BPROUTING.fields_by_name['to_loc_id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_BPROUTING.fields_by_name['route'].message_type = common_dot_message_dot_routing_dot_routing__pb2._ROUTINGRESPONSE
_BPROUTING.fields_by_name['pathpoint'].message_type = common_dot_message_dot_geometry__pb2._POINTENU
_BPROUTING.fields_by_name['destination'].message_type = _DESTINATIONINFO
_BPNETWORK.fields_by_name['routing'].message_type = _BPROUTING
DESCRIPTOR.message_types_by_name['DestinationInfo'] = _DESTINATIONINFO
DESCRIPTOR.message_types_by_name['BPRouting'] = _BPROUTING
DESCRIPTOR.message_types_by_name['BPNetwork'] = _BPNETWORK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DestinationInfo = _reflection.GeneratedProtocolMessageType('DestinationInfo', (_message.Message,), dict(
  DESCRIPTOR = _DESTINATIONINFO,
  __module__ = 'common.message.dispatch.bp_network_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.dispatch.DestinationInfo)
  ))
_sym_db.RegisterMessage(DestinationInfo)

BPRouting = _reflection.GeneratedProtocolMessageType('BPRouting', (_message.Message,), dict(
  DESCRIPTOR = _BPROUTING,
  __module__ = 'common.message.dispatch.bp_network_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.dispatch.BPRouting)
  ))
_sym_db.RegisterMessage(BPRouting)

BPNetwork = _reflection.GeneratedProtocolMessageType('BPNetwork', (_message.Message,), dict(
  DESCRIPTOR = _BPNETWORK,
  __module__ = 'common.message.dispatch.bp_network_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.dispatch.BPNetwork)
  ))
_sym_db.RegisterMessage(BPNetwork)


# @@protoc_insertion_point(module_scope)
