#C11Demo、C11UnicodeDemo C11TableDemo C11Algorithm
target=C11Algorithm
cflags=--std=c++11 -g
cc=g++

#src=$(wildcard *.cpp)
src=$(target).cpp

all:
	echo $(src)
	$(cc) -o $(target) $(cflags) $(src)
clean:
	rm -rf $(target) 
	
	
	
