# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/scheduler/scheduler_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/scheduler/scheduler_request.proto',
  package='citibot.common.message',
  syntax='proto2',
  serialized_pb=_b('\n)message/scheduler/scheduler_request.proto\x12\x16\x63itibot.common.message\"\x82\x01\n\x10SchedulerRequest\x12:\n\x04type\x18\x01 \x01(\x0e\x32,.citibot.common.message.SchedulerRequestType\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\t\x12\x10\n\x05reply\x18\x04 \x01(\x05:\x01\x30*\x88\x01\n\x14SchedulerRequestType\x12\x15\n\x11REQUEST_CACC_FORM\x10\x00\x12\x15\n\x11REQUEST_CACC_JOIN\x10\x01\x12\x16\n\x12REQUEST_CACC_LEAVE\x10\x02\x12\x18\n\x14REQUEST_CACC_DISBAND\x10\x03\x12\x10\n\x0cREQUEST_TIPS\x10\x04')
)

_SCHEDULERREQUESTTYPE = _descriptor.EnumDescriptor(
  name='SchedulerRequestType',
  full_name='citibot.common.message.SchedulerRequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST_CACC_FORM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_CACC_JOIN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_CACC_LEAVE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_CACC_DISBAND', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_TIPS', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=203,
  serialized_end=339,
)
_sym_db.RegisterEnumDescriptor(_SCHEDULERREQUESTTYPE)

SchedulerRequestType = enum_type_wrapper.EnumTypeWrapper(_SCHEDULERREQUESTTYPE)
REQUEST_CACC_FORM = 0
REQUEST_CACC_JOIN = 1
REQUEST_CACC_LEAVE = 2
REQUEST_CACC_DISBAND = 3
REQUEST_TIPS = 4



_SCHEDULERREQUEST = _descriptor.Descriptor(
  name='SchedulerRequest',
  full_name='citibot.common.message.SchedulerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='citibot.common.message.SchedulerRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='citibot.common.message.SchedulerRequest.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='citibot.common.message.SchedulerRequest.options', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reply', full_name='citibot.common.message.SchedulerRequest.reply', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=200,
)

_SCHEDULERREQUEST.fields_by_name['type'].enum_type = _SCHEDULERREQUESTTYPE
DESCRIPTOR.message_types_by_name['SchedulerRequest'] = _SCHEDULERREQUEST
DESCRIPTOR.enum_types_by_name['SchedulerRequestType'] = _SCHEDULERREQUESTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchedulerRequest = _reflection.GeneratedProtocolMessageType('SchedulerRequest', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULERREQUEST,
  __module__ = 'message.scheduler.scheduler_request_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.SchedulerRequest)
  ))
_sym_db.RegisterMessage(SchedulerRequest)


# @@protoc_insertion_point(module_scope)
