# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message/map/map_mark_polygon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.message.map import map_geometry_pb2 as common_dot_message_dot_map_dot_map__geometry__pb2
from common.message.map import map_id_pb2 as common_dot_message_dot_map_dot_map__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message/map/map_mark_polygon.proto',
  package='citibot.common.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n)common/message/map/map_mark_polygon.proto\x12\x14\x63itibot.common.hdmap\x1a%common/message/map/map_geometry.proto\x1a\x1f\x63ommon/message/map/map_id.proto\"\x8d\x03\n\x0bMarkPolygon\x12$\n\x02id\x18\x01 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12.\n\x07polygon\x18\x02 \x01(\x0b\x32\x1d.citibot.common.hdmap.Polygon\x12,\n\noverlap_id\x18\x03 \x03(\x0b\x32\x18.citibot.common.hdmap.Id\x12\x34\n\x04type\x18\x04 \x01(\x0e\x32&.citibot.common.hdmap.MarkPolygon.Type\"\xc3\x01\n\x04Type\x12\x10\n\x0c\x42RIDGE_ABOVE\x10\x01\x12\x0c\n\x08\x44OWNHILL\x10\x02\x12\n\n\x06UPHILL\x10\x03\x12\x10\n\x0cTOLL_STATION\x10\x04\x12\x0f\n\x0b\x42US_STATION\x10\x05\x12\x1b\n\x17\x45MERGENCY_PARKING_STRIP\x10\x06\x12\x12\n\x0e\x46ORBIDDEN_AREA\x10\x07\x12\r\n\tDUMP_AREA\x10\x08\x12\x0f\n\x0bNARROW_ROAD\x10\t\x12\r\n\tFREE_AREA\x10\x1c\x12\x0c\n\x08\x43\x43P_AREA\x10\x1e')
  ,
  dependencies=[common_dot_message_dot_map_dot_map__geometry__pb2.DESCRIPTOR,common_dot_message_dot_map_dot_map__id__pb2.DESCRIPTOR,])



_MARKPOLYGON_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='citibot.common.hdmap.MarkPolygon.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BRIDGE_ABOVE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWNHILL', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPHILL', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOLL_STATION', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUS_STATION', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EMERGENCY_PARKING_STRIP', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORBIDDEN_AREA', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DUMP_AREA', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NARROW_ROAD', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FREE_AREA', index=9, number=28,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CCP_AREA', index=10, number=30,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=342,
  serialized_end=537,
)
_sym_db.RegisterEnumDescriptor(_MARKPOLYGON_TYPE)


_MARKPOLYGON = _descriptor.Descriptor(
  name='MarkPolygon',
  full_name='citibot.common.hdmap.MarkPolygon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='citibot.common.hdmap.MarkPolygon.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='citibot.common.hdmap.MarkPolygon.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overlap_id', full_name='citibot.common.hdmap.MarkPolygon.overlap_id', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='citibot.common.hdmap.MarkPolygon.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MARKPOLYGON_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=537,
)

_MARKPOLYGON.fields_by_name['id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_MARKPOLYGON.fields_by_name['polygon'].message_type = common_dot_message_dot_map_dot_map__geometry__pb2._POLYGON
_MARKPOLYGON.fields_by_name['overlap_id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_MARKPOLYGON.fields_by_name['type'].enum_type = _MARKPOLYGON_TYPE
_MARKPOLYGON_TYPE.containing_type = _MARKPOLYGON
DESCRIPTOR.message_types_by_name['MarkPolygon'] = _MARKPOLYGON
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MarkPolygon = _reflection.GeneratedProtocolMessageType('MarkPolygon', (_message.Message,), dict(
  DESCRIPTOR = _MARKPOLYGON,
  __module__ = 'common.message.map.map_mark_polygon_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.hdmap.MarkPolygon)
  ))
_sym_db.RegisterMessage(MarkPolygon)


# @@protoc_insertion_point(module_scope)
