# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message/map/map_station.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.message.map import map_geometry_pb2 as common_dot_message_dot_map_dot_map__geometry__pb2
from common.message.map import map_id_pb2 as common_dot_message_dot_map_dot_map__id__pb2
from common.message.map import map_lane_pb2 as common_dot_message_dot_map_dot_map__lane__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message/map/map_station.proto',
  package='citibot.common.hdmap',
  syntax='proto2',
  serialized_pb=_b('\n$common/message/map/map_station.proto\x12\x14\x63itibot.common.hdmap\x1a%common/message/map/map_geometry.proto\x1a\x1f\x63ommon/message/map/map_id.proto\x1a!common/message/map/map_lane.proto\"\xf3\x02\n\x07Station\x12$\n\x02id\x18\x01 \x01(\x0b\x32\x18.citibot.common.hdmap.Id\x12.\n\x07polygon\x18\x02 \x01(\x0b\x32\x1d.citibot.common.hdmap.Polygon\x12\x33\n\x0cparking_zone\x18\x03 \x03(\x0b\x32\x1d.citibot.common.hdmap.Polygon\x12G\n\x17\x63rossings_boundary_type\x18\x04 \x03(\x0b\x32&.citibot.common.hdmap.LaneBoundaryType\x12,\n\noverlap_id\x18\x05 \x03(\x0b\x32\x18.citibot.common.hdmap.Id\x12\x38\n\x04type\x18\x64 \x02(\x0e\x32\".citibot.common.hdmap.Station.Type:\x06\x44IRECT\x12\x0c\n\x04name\x18\x65 \x01(\t\"\x1e\n\x04Type\x12\n\n\x06\x44IRECT\x10\x01\x12\n\n\x06HARBOR\x10\x02')
  ,
  dependencies=[common_dot_message_dot_map_dot_map__geometry__pb2.DESCRIPTOR,common_dot_message_dot_map_dot_map__id__pb2.DESCRIPTOR,common_dot_message_dot_map_dot_map__lane__pb2.DESCRIPTOR,])



_STATION_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='citibot.common.hdmap.Station.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIRECT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HARBOR', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=511,
  serialized_end=541,
)
_sym_db.RegisterEnumDescriptor(_STATION_TYPE)


_STATION = _descriptor.Descriptor(
  name='Station',
  full_name='citibot.common.hdmap.Station',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='citibot.common.hdmap.Station.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='polygon', full_name='citibot.common.hdmap.Station.polygon', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parking_zone', full_name='citibot.common.hdmap.Station.parking_zone', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crossings_boundary_type', full_name='citibot.common.hdmap.Station.crossings_boundary_type', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='overlap_id', full_name='citibot.common.hdmap.Station.overlap_id', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='citibot.common.hdmap.Station.type', index=5,
      number=100, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='citibot.common.hdmap.Station.name', index=6,
      number=101, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATION_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=541,
)

_STATION.fields_by_name['id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_STATION.fields_by_name['polygon'].message_type = common_dot_message_dot_map_dot_map__geometry__pb2._POLYGON
_STATION.fields_by_name['parking_zone'].message_type = common_dot_message_dot_map_dot_map__geometry__pb2._POLYGON
_STATION.fields_by_name['crossings_boundary_type'].message_type = common_dot_message_dot_map_dot_map__lane__pb2._LANEBOUNDARYTYPE
_STATION.fields_by_name['overlap_id'].message_type = common_dot_message_dot_map_dot_map__id__pb2._ID
_STATION.fields_by_name['type'].enum_type = _STATION_TYPE
_STATION_TYPE.containing_type = _STATION
DESCRIPTOR.message_types_by_name['Station'] = _STATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Station = _reflection.GeneratedProtocolMessageType('Station', (_message.Message,), dict(
  DESCRIPTOR = _STATION,
  __module__ = 'common.message.map.map_station_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.hdmap.Station)
  ))
_sym_db.RegisterMessage(Station)


# @@protoc_insertion_point(module_scope)
