# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message/gateway/remote_cmd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.message.control import control_cmd_pb2 as common_dot_message_dot_control_dot_control__cmd__pb2
from common.message.function_manage import manage_info_pb2 as common_dot_message_dot_function__manage_dot_manage__info__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message/gateway/remote_cmd.proto',
  package='citibot.common.message',
  syntax='proto2',
  serialized_pb=_b('\n\'common/message/gateway/remote_cmd.proto\x12\x16\x63itibot.common.message\x1a(common/message/control/control_cmd.proto\x1a\x30\x63ommon/message/function_manage/manage_info.proto\"{\n\tRemoteCmd\x12\x35\n\ndevice_cmd\x18\x01 \x01(\x0b\x32!.citibot.common.message.DeviceCmd\x12\x37\n\x0b\x63ontrol_cmd\x18\x02 \x01(\x0b\x32\".citibot.common.message.ControlCmd')
  ,
  dependencies=[common_dot_message_dot_control_dot_control__cmd__pb2.DESCRIPTOR,common_dot_message_dot_function__manage_dot_manage__info__pb2.DESCRIPTOR,])




_REMOTECMD = _descriptor.Descriptor(
  name='RemoteCmd',
  full_name='citibot.common.message.RemoteCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_cmd', full_name='citibot.common.message.RemoteCmd.device_cmd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control_cmd', full_name='citibot.common.message.RemoteCmd.control_cmd', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=282,
)

_REMOTECMD.fields_by_name['device_cmd'].message_type = common_dot_message_dot_function__manage_dot_manage__info__pb2._DEVICECMD
_REMOTECMD.fields_by_name['control_cmd'].message_type = common_dot_message_dot_control_dot_control__cmd__pb2._CONTROLCMD
DESCRIPTOR.message_types_by_name['RemoteCmd'] = _REMOTECMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoteCmd = _reflection.GeneratedProtocolMessageType('RemoteCmd', (_message.Message,), dict(
  DESCRIPTOR = _REMOTECMD,
  __module__ = 'common.message.gateway.remote_cmd_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.RemoteCmd)
  ))
_sym_db.RegisterMessage(RemoteCmd)


# @@protoc_insertion_point(module_scope)
