# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/message/ap2ros/data_record_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.message import header_pb2 as common_dot_message_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/message/ap2ros/data_record_status.proto',
  package='citibot.common.message',
  syntax='proto2',
  serialized_pb=_b('\n.common/message/ap2ros/data_record_status.proto\x12\x16\x63itibot.common.message\x1a\x1b\x63ommon/message/header.proto\"\xa6\x01\n\x13\x44\x61taRecordStatusMsg\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.citibot.common.message.Header\x12\r\n\x05token\x18\x02 \x01(\x04\x12;\n\rrecord_status\x18\x03 \x01(\x0e\x32$.citibot.common.message.RecordStatus\x12\x13\n\x0binstance_id\x18\x04 \x03(\x05\"^\n\x10\x44\x61taRecordStatus\x12\r\n\x05token\x18\x01 \x01(\x04\x12;\n\rrecord_status\x18\x02 \x01(\x0e\x32$.citibot.common.message.RecordStatus\"\xb1\x02\n\rDataRecordMsg\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x1e.citibot.common.message.Header\x12\x46\n\x14\x63ommon_record_status\x18\x02 \x01(\x0b\x32(.citibot.common.message.DataRecordStatus\x12\x46\n\x14\x63yclic_record_status\x18\x03 \x01(\x0b\x32(.citibot.common.message.DataRecordStatus\x12K\n\x19\x63losed_loop_record_status\x18\x04 \x01(\x0b\x32(.citibot.common.message.DataRecordStatus\x12\x13\n\x0binstance_id\x18\x14 \x03(\x05*C\n\x0cRecordStatus\x12\r\n\tRECORDING\x10\x00\x12\x11\n\rRECORD_FINISH\x10\x01\x12\x11\n\rRECORD_FAILED\x10\x02')
  ,
  dependencies=[common_dot_message_dot_header__pb2.DESCRIPTOR,])

_RECORDSTATUS = _descriptor.EnumDescriptor(
  name='RecordStatus',
  full_name='citibot.common.message.RecordStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RECORDING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECORD_FINISH', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECORD_FAILED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=676,
  serialized_end=743,
)
_sym_db.RegisterEnumDescriptor(_RECORDSTATUS)

RecordStatus = enum_type_wrapper.EnumTypeWrapper(_RECORDSTATUS)
RECORDING = 0
RECORD_FINISH = 1
RECORD_FAILED = 2



_DATARECORDSTATUSMSG = _descriptor.Descriptor(
  name='DataRecordStatusMsg',
  full_name='citibot.common.message.DataRecordStatusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='citibot.common.message.DataRecordStatusMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='citibot.common.message.DataRecordStatusMsg.token', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='record_status', full_name='citibot.common.message.DataRecordStatusMsg.record_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='citibot.common.message.DataRecordStatusMsg.instance_id', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=270,
)


_DATARECORDSTATUS = _descriptor.Descriptor(
  name='DataRecordStatus',
  full_name='citibot.common.message.DataRecordStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='citibot.common.message.DataRecordStatus.token', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='record_status', full_name='citibot.common.message.DataRecordStatus.record_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=366,
)


_DATARECORDMSG = _descriptor.Descriptor(
  name='DataRecordMsg',
  full_name='citibot.common.message.DataRecordMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='citibot.common.message.DataRecordMsg.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='common_record_status', full_name='citibot.common.message.DataRecordMsg.common_record_status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cyclic_record_status', full_name='citibot.common.message.DataRecordMsg.cyclic_record_status', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='closed_loop_record_status', full_name='citibot.common.message.DataRecordMsg.closed_loop_record_status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='citibot.common.message.DataRecordMsg.instance_id', index=4,
      number=20, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=674,
)

_DATARECORDSTATUSMSG.fields_by_name['header'].message_type = common_dot_message_dot_header__pb2._HEADER
_DATARECORDSTATUSMSG.fields_by_name['record_status'].enum_type = _RECORDSTATUS
_DATARECORDSTATUS.fields_by_name['record_status'].enum_type = _RECORDSTATUS
_DATARECORDMSG.fields_by_name['header'].message_type = common_dot_message_dot_header__pb2._HEADER
_DATARECORDMSG.fields_by_name['common_record_status'].message_type = _DATARECORDSTATUS
_DATARECORDMSG.fields_by_name['cyclic_record_status'].message_type = _DATARECORDSTATUS
_DATARECORDMSG.fields_by_name['closed_loop_record_status'].message_type = _DATARECORDSTATUS
DESCRIPTOR.message_types_by_name['DataRecordStatusMsg'] = _DATARECORDSTATUSMSG
DESCRIPTOR.message_types_by_name['DataRecordStatus'] = _DATARECORDSTATUS
DESCRIPTOR.message_types_by_name['DataRecordMsg'] = _DATARECORDMSG
DESCRIPTOR.enum_types_by_name['RecordStatus'] = _RECORDSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataRecordStatusMsg = _reflection.GeneratedProtocolMessageType('DataRecordStatusMsg', (_message.Message,), dict(
  DESCRIPTOR = _DATARECORDSTATUSMSG,
  __module__ = 'common.message.ap2ros.data_record_status_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.DataRecordStatusMsg)
  ))
_sym_db.RegisterMessage(DataRecordStatusMsg)

DataRecordStatus = _reflection.GeneratedProtocolMessageType('DataRecordStatus', (_message.Message,), dict(
  DESCRIPTOR = _DATARECORDSTATUS,
  __module__ = 'common.message.ap2ros.data_record_status_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.DataRecordStatus)
  ))
_sym_db.RegisterMessage(DataRecordStatus)

DataRecordMsg = _reflection.GeneratedProtocolMessageType('DataRecordMsg', (_message.Message,), dict(
  DESCRIPTOR = _DATARECORDMSG,
  __module__ = 'common.message.ap2ros.data_record_status_pb2'
  # @@protoc_insertion_point(class_scope:citibot.common.message.DataRecordMsg)
  ))
_sym_db.RegisterMessage(DataRecordMsg)


# @@protoc_insertion_point(module_scope)
